// Code generated by tygo. DO NOT EDIT.

//////////
// source: noComments.go

export type UserRole = string;
export const UserRoleDefault: UserRole = "viewer";
export const UserRoleEditor: UserRole = "editor";
export interface User {
  id: string | null;
}
