// Code generated by tygo. DO NOT EDIT.

//////////
// source: author.go

export interface AuthorBookListing {
  author_name: string;
  written_books: Book[];
}
export interface AuthorWithInheritance<T extends number /* int */> {
  id: T;
}

//////////
// source: book.go

export type ISBN = string | null;
export interface Chapter {
  /**
   * Chapter title
   */
  title: string;
  /**
   * The amount of words in this chapter
   */
  number_of_words: number /* uint */;
}
export interface Book {
  book_id: string; // A line comment about BookID that should be kept.
  title: string;
  /**
   * ISBN identifier of the book, null if not known.
   */
  isbn: ISBN;
  genre: 'novel' | 'crime' | 'fantasy';
  chapters: Chapter[];
  published_at?: string /* RFC 3339 formatted */;
}
export interface TextBook<T extends number /* int */> extends Book {
  pages: T;
}
