// Code generated by tygo. DO NOT EDIT.

//////////
// source: book.go

/**
 * Chapter some random docs
 */
export interface Chapter {
  /**
   * Chapter title
   */
  title: string;
  /**
   * The amount of words in this chapter
   */
  number_of_words: number /* uint */;
}
