// Code generated by tygo. DO NOT EDIT.
import * as bookapp from "../bookstore"

//////////
// source: inheritance.go

export interface Base {
  name: string;
}
export interface Base2<T extends string | number /* int */> {
  id: T;
}
export interface Base3<T extends string, X extends number /* int */> {
  class: T;
  level: X;
}
export interface Other<T extends number /* int */, X extends string> extends Base, Base2<T>, Partial<Base3<X, T>>, bookapp.Book, bookapp.TextBook<T> {
  otherWithBase: Base;
  otherWithBase2: Base2<X>;
  otherValue: string;
  author: bookapp.AuthorWithInheritance<T>;
}
