// Code generated by tygo. DO NOT EDIT.

//////////
// source: custom.go

 export type StructAsTuple=[a:number, b:number, c:string]
/**
 * CustomMarshalled illustrates getting tygo to emit literal text/
 * This solves the problem of a struct field being marshalled into a tuple.
 */
export interface CustomMarshalled {
  content: StructAsTuple[];
}
