// Code generated by tygo. DO NOT EDIT.

//////////
// source: interface.go

/**
 * Plain interfaces should output the unknown type, which is `any` by default but can also be configured as `unknown`).
 */
export type InterfaceOnly = any;
