// Code generated by tygo. DO NOT EDIT.

//////////
// source: preserveTypeComments.go

/**
 * Type comments are kept, unless configured to "none"
 */
export type UserRole = string;
/**
 * UserRoleDefault is "viewer"
 */
export const UserRoleDefault: UserRole = "viewer";
/**
 * UserRoleEditor can edit other users
 */
export const UserRoleEditor: UserRole = "editor";
export interface User {
  /**
   * Struct field comments are preserved unless configured to "none"
   */
  id: string | null;
}
