// Code generated by tygo. DO NOT EDIT.

//////////
// source: preserveTypeComments.go

/**
 * Type comments are preserved, unless configured to "none"
 */
export type UserRole = string;
/**
 * Const comments are preserved, unless configured to "none"
 */
export const UserRoleDefault: UserRole = "viewer";
export const UserRoleEditor: UserRole = "editor";
export interface User {
  /**
   * Struct field comments are preserved unless configured to "none"
   */
  id: string | null;
}
