// Code generated by tygo. DO NOT EDIT.

//////////
// source: yaml.go

export interface YAMLTest {
  id: string;
  prefs: { [key: string]: {
    foo: number /* uint32 */;
  }};
  address?: string;
  nickname?: string;
  thiswillgetlowercased: string;
}
