// Code generated by tygo. DO NOT EDIT.

//////////
// source: generic.go

/**
 * Comment for UnionType
 */
export type UnionType = 
    /**
     * Comment for fields are possible
     */
    number /* uint64 */ | string | boolean | undefined // comment after
;
export type Derived = 
    number /* int */ | string // Line comment
;
export type Any = 
    string | any;
export type Empty = any;
export type Something = any;
export interface EmptyStruct {
}
export interface Foo<V extends any, PT extends (V | undefined), Unused extends string> {
  Val: V;
  /**
   * Comment for ptr field
   */
  Ptr: PT; // ptr line comment
}
export interface ABCD<A extends string, B extends string, C extends string, D extends number /* int64 */ | boolean> {
  a: A;
  b: B;
  c: C;
  d: D;
}
