// Code generated by tygo. DO NOT EDIT.

//////////
// source: functions.go

export type FunctionWithParam = (arg_0: number /* int */) => void;
export type FunctionWithNamedParameters = (foo: number /* int */, bar: number /* int */) => void;
export type FunctionWithSliceParameter = (arg_0: number /* int */[]) => void;
export type FunctionWithVariadic = (arg_0: number /* int */, ...arg_1: number /* int */[]) => void;
export type FunctionWithReturn = (arg_0: number /* int */) => number /* int */;
export type FunctionWithMultipleReturn = (arg_0: number /* int */) => any;
export type FunctionWithMultipleReturnAndNamedReturn = (arg_0: number /* int */) => any;
export type FunctionAlias = (arg_0: number /* int */) => void;
export type FunctionWithFunctionParameter = (arg_0: (arg_0: number /* int */) => void) => void;
export type FunctionWithFunctionReturned = () => (arg_0: number /* int */) => number /* int */;
export type FuncWithPointerReceiver = (arg_0: string | undefined) => void;
