// Code generated by tygo. DO NOT EDIT.
import * as bookapp from "../bookstore"

//////////
// source: embed.go

/**
 * TokenType Built-in type alias
 */
export type TokenType = string;
/**
 * Reference struct type
 */
export interface Reference {
  foo: string;
}
export interface Base {
  id: string;
}
export interface StructEmbed extends Base {
  tokenType: TokenType; // built-in type field without `tstype:"extends"`
  reference: Reference; // embed struct without `tstype:"extends"`
  other_reference: Reference;
  bar: string;
  book: bookapp.Book; // embed external struct without `tstype:"extends"`
  chapter?: bookapp.Chapter; // embed external struct pointer without `tstype:"extends"`
}
