// Code generated by tygo. DO NOT EDIT.
import * as bookapp from "../bookstore"

//////////
// source: embed.go

/**
 * TokenType Built-in type alias
 */
export type TokenType = string;
export interface StructEmbed extends Base {
  tokenType: TokenType; // built-in type field without `tstype:"extends"`
  reference: Reference; // embed struct without `tstype:"extends"`
  other_reference: Reference;
  bar: string;
  book: bookapp.Book; // embed external struct without `tstype:"extends"`
  chapter?: bookapp.Chapter; // embed external struct pointer without `tstype:"extends"`
}

//////////
// source: types.go
/*
Package embed types defined in the Go file after the parsed file in the same package
*/

export interface Base {
  id: string;
}
/**
 * Reference struct type, defined after embed.go, the same pkg but not the same file
 */
export interface Reference {
  foo: string;
}
